name: Déploiement à la demande

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-site-preprod:
    name: Déploie le site sur la preprod
    environment: preprod
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.20
      - name: Login into registry
        run: earthly --use-inline-cache +docker-dev-login --GH_USER=${{ secrets.GH_USER }} --GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Build and push front deps image
        run: > 
          earthly 
          --use-inline-cache --save-inline-cache --push 
          --platform=linux/amd64 
          +front-deps-builder

      - name: Build and push site image
        run: >
          earthly 
          --use-inline-cache --save-inline-cache --push 
          --platform=linux/amd64 
          +site-build
          --ENV_NAME=preprod
          --ANON_KEY=${{ secrets.ANON_KEY }} --API_URL=${{ secrets.API_URL }}
          --STRAPI_KEY=${{ secrets.STRAPI_KEY }} --STRAPI_URL=${{ secrets.STRAPI_URL }}

      - name: Deploy site on koyeb
        run: >
          earthly 
          --use-inline-cache 
          +site-deploy
          --ENV_NAME=preprod
          --KOYEB_API_KEY=${{ secrets.KOYEB_API_KEY }}

  deploy-app-preprod:
    name: Déploie l'app sur la preprod
    environment: preprod
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.20
      - name: Login into registry
        run: earthly --use-inline-cache +docker-dev-login --GH_USER=${{ secrets.GH_USER }} --GH_TOKEN=${{ secrets.GH_TOKEN }}

      - name: Build and push front deps image
        run: >
          earthly 
          --use-inline-cache --save-inline-cache --push 
          --platform=linux/amd64 
          +front-deps-builder

      - name: Build and push app image
        run: >
          earthly 
          --use-inline-cache --save-inline-cache --push 
          --platform=linux/amd64 
          +app-build
          --ENV_NAME=preprod
          --ANON_KEY=${{ secrets.ANON_KEY }} --API_URL=${{ secrets.API_URL }}

      - name: Deploy app on koyeb
        run: > 
          earthly 
          --use-inline-cache 
          +app-deploy
          --ENV_NAME=preprod
          --KOYEB_API_KEY=${{ secrets.KOYEB_API_KEY }}
