name: Publie le storybook sur chromatic

on:
  push:
#    paths:
#      - '**.storyshot'

# interrompt le workflow précédent si un nouveau est déclenché pour le même
# commit (cas push + ouverture PR)
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    env:
      client-directory: ./app.territoiresentransitions.react
      LANG: 'fr_FR.UTF-8'
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      - uses: actions/checkout@v1

      - name: Fixe la langue de l'environnement
        run: |
          sudo locale-gen ${{env.LANG}}
          sudo update-locale LANG=${{env.LANG}}

      - name: Copie les variables d'environnement
        run: sh make_dot_env.sh

      - name: Installe les dépendances.
        run: npm install
        working-directory: ${{env.client-directory}}

      - name: Publication sur Chromatic
        uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ${{env.client-directory}}
