name: Test Client

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:

# interrompt le workflow précédent si un nouveau est déclenché pour le même
# commit (cas push + ouverture PR)
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  client-test:
    name: Client unit tests
    runs-on: ubuntu-latest
    env:
      LANG: 'fr_FR.UTF-8'
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # fixe la langue de l'environnement de test : permet de faire passer les
      # tests de composant utilisant des fonctions telles que toLocaleString()
      - name: Set locale
        run: |
          sudo locale-gen ${{env.LANG}}
          sudo update-locale LANG=${{env.LANG}}

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Run test container.
      - name: Run npm tests in docker compose
        run: docker-compose run client-test
