name: Test Business

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  business-test:
    name: Business tests
    runs-on: ubuntu-latest
    env:
      business-directory:  ./business
      datalayer-directory: ./data_layer
      datalayer-docker-directory: ./data_layer
      SUPABASE_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjI3MjA4NTQwLCJleHAiOjE5NzQzNjM3NDB9.pkT3PNpO4DtO45Ac5HK_TKCx8sGLgNtV__pr_ZrRSAU
      SUPABASE_URL: http://localhost:8000
      SUPABASE_WS: ws://localhost:8000

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Launch docker
      - name: Launch docker
        run: |
          cp .env.sample .env
          docker-compose up --build -d
        working-directory: ${{env.datalayer-docker-directory}}

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      # Install the dependencies manager.
      - name: Install pipenv
        run: |
          cp .env.sample .env
          python -m pip install --upgrade pipenv wheel
            pipenv install
            pipenv install --dev
        working-directory: ${{env.business-directory}}


      # [Prepare DB] Insert fakes
      - name: Insert fake data in database
        run: sh insert_all.sh
        working-directory: ${{env.datalayer-directory}}

      # Restart postgres service
      - name: Restart postgres service
        run: docker-compose restart rest
        working-directory: ${{env.datalayer-docker-directory}}

      # Use Pytest to run tests
      - name: Tests
        run:  pipenv run pytest tests
        working-directory: ${{env.business-directory}}
