name: Test

on:
  push:
    branches-ignore:
      - production

jobs:
  test-codegen:
    runs-on: ubuntu-latest
    env:
      working-directory: ./codegen

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip --no-cache-dir install poetry

      - name: Install dependencies
        run: poetry install
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: poetry run pytest
        working-directory: ${{env.working-directory}}
  end-to-end:
    runs-on: ubuntu-latest
    env:
      working-directory:  ./app.territoiresentransitions.fr

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run export
          start: npx serve __sapper__/export
        working-directory: ${{env.working-directory}}
