name: Test Business

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  business-test:
    name: Business tests
    runs-on: ubuntu-latest
    env:
      business-directory:  ./business
      datalayer-directory: ./data_layer
      datalayer-docker-directory: ./data_layer
      SUPABASE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_URL: http://localhost:8000
      SUPABASE_WS: ws://localhost:8000

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Launch docker
      - name: Launch docker
        run: |
          cp .env.sample .env
          docker-compose up --build -d
        working-directory: ${{env.datalayer-docker-directory}}

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      # Install the dependencies manager.
      - name: Install pipenv
        run: |
          cp .env.sample .env
          python -m pip install --upgrade pipenv wheel
            pipenv install
            pipenv install --dev
        working-directory: ${{env.business-directory}}

      # Wait for the rest container
      - name: Wait for datalayer
        run: |
          sh wait_for_rest.sh
        working-directory: ${{env.datalayer-docker-directory}}

      # Use Pytest to run tests
      - name: Tests
        run:  pipenv run pytest tests
        working-directory: ${{env.business-directory}}
