name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test-routers:
    runs-on: ubuntu-latest

    env:
      AUTH_DISABLED_DUMMY_USER: YES
      working-directory: ./api

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Restore cache or create a new one for all dependencies installed with
      # Python.
      - name: Set up Python cache
        uses: actions/cache@v2
        env:
          python-tools-cache-name: python-tools-cache
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-${{ env.python-tools-cache-name }}-${{ env.python-version }}
          restore-keys: |
            ${{ runner.os }}-${{ env.python-tools-cache-name }}
            ${{ runner.os }}-

      # Restore cache or create a new one for all dependencies installed with
      # Pipenv
      - name: Set up Pipenv cache
        uses: actions/cache@v2
        env:
          pipenv-cache-name: pipenv-cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-${{ env.pipenv-cache-name }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pipenv-cache-name }}
            ${{ runner.os }}-

      # cf. https://github.com/actions/setup-python
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      # Install the dependencies manager.
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      # Install the project's dependencies.
      - name: Install dependencies
        run: |
          pipenv install
          pipenv install --dev

      # Run tests
      - name: Run tests
        run: pipenv run pytest

