name: Tests end-to-end

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  end-to-end-test:
    name: End-to-end tests
    runs-on: ubuntu-latest
    env:
      e2e-directory: ./e2e
      datalayer-directory: ./data_layer
      project-docker-directory: ./
      SUPABASE_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}
      SUPABASE_URL: http://localhost:8000
      ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}
      SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      REACT_APP_CRISP_WEBSITE_ID: 96fe7866-d005-4623-80b1-bd772e99855c
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Build docker
      - name: Build docker
        run: docker-compose build
        working-directory: ${{env.project-docker-directory}}

      # Tear down docker
      - name: Down docker
        run: docker-compose down
        working-directory: ${{env.project-docker-directory}}

      # Launch docker
      - name: Launch docker
        run: docker-compose up -d
        working-directory: ${{env.project-docker-directory}}

      # Wait for the rest container
      - name: Wait for rest
        run: sh scripts/wait_for_rest.sh
        working-directory: ${{env.datalayer-directory}}

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{env.e2e-directory}}
