name: Test Client

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  client-test:
    name: Client unit tests
    runs-on: ubuntu-latest
    env:
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Run test container.
      - name: Run npm tests in docker compose
        run: docker-compose run client-test
