name: Test Client

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  client-test:
    name: Client unit tests
    runs-on: ubuntu-latest
    env:
      app-directory: ./app.territoiresentransitions.react
      datalayer-directory: ./data_layer
      datalayer-docker-directory: ./data_layer
      SUPABASE_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}
      SUPABASE_URL: http://localhost:8000
      REACT_APP_CRISP_WEBSITE_ID: 96fe7866-d005-4623-80b1-bd772e99855c
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ${{env.app-directory}}/package-lock.json

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Launch docker
      - name: Launch docker
        run: docker-compose up --build -d
        working-directory: ${{env.datalayer-docker-directory}}

      # Install app dependencies
      - name: Install client dependencies
        run: npm install
        working-directory: ${{env.app-directory}}

      # Wait for the rest container
      - name: Wait for datalayer
        run: sh wait_for_rest.sh
        working-directory: ${{env.datalayer-docker-directory}}

      # Run client unit tests
      - name: Run unit tests
        run: npm run test
        working-directory: ${{env.app-directory}}
        env:
          REACT_APP_SUPABASE_KEY: ${{env.SUPABASE_KEY}}
          REACT_APP_SUPABASE_URL: ${{env.SUPABASE_URL}}
