name: Conversion des markdowns

on: workflow_dispatch

jobs:
  update-json:
    name: Lecture et conversion des fichiers markdown en JSON
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Convertit les fichiers markdown en JSON
        run: docker compose run --no-deps business-parse-content

      - name: Run datalayer loader
        run: sh make_dot_env.sh && docker-compose run loader
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
          SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

      - name: Commit les fichiers JSON
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Generated preuves from updated markdowns.
