name: Update actions

on:
  push:
    paths:
      - "markdown/referentiel/cae/*.md"
  pull_request:
    branches-ignore:
      - production
      - production-static

jobs:
  parse-actions:
    name: Lecture et conversion des fichiers markdown
    runs-on: ubuntu-latest

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # TODO ! 
      # # Execute CLI on local datalayer if branch not in [upcoming-sandbox, upcoming-production]
      # - name: Execute parsing scripts to generate JSON files in data_layer/content
      #   run: docker compose run --no-deps business-parse-actions-cae

      # # Check that datalayer loader runs  
      # - name: Run datalayer loader 
      #   run: docker-compose run loader

      # # Commit changes
      # - name: Commit generated JSON files
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     default_author: github_actions
      #     message: Generated actions from updated markdowns.
